vmconf:
  machine_name: 'Vagrant Magento 2'
  network_ip: '192.168.56.12'
  host_name: 'zepgram'
  memory: '4096'
  cpus: '1'
  mount: 'nfs'
  path: 'root'
  provision: 'all'
composer:
  username: '19321d8091b926ae54cc8f1c18437c34'
  password: '70efcef3cc298de6c6903c0a208545a2'
git:
  name: 'develophper'
  email: 'thomasr.ryan.1990@gmail.com'
  host: 'github.com'
#  repository: 'ssh://git@github.com:project-name.git'
  repository: 'ssh://git@github.com:Gravytrain-UK/sh-magento.git'
magento:
  url: 'dev.magento.com'
  source: 'composer'
  edition: 'community'
  version: '2.2.3'
  php_version: '7.0'
  sample: 'false'
  mode: 'developer'
  currency: 'USD'
  language: 'en_US'
  time_zone: 'America/New_York'
  crypt_key: ''
